# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ANDROID' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ANDROID
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTLinkingIOS',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'ANDROID-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-ble-plx', :path => '../node_modules/react-native-ble-plx'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'ANDROIDTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ANDROID-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ANDROID-tvOS



end
